build_from:
  aarch64: homeassistant/aarch64-base-python:latest
  amd64: homeassistant/amd64-base-python:latest
  armhf: homeassistant/armhf-base-python:latest
  armv7: homeassistant/armv7-base-python:latest
  i386: homeassistant/i386-base-python:latest
args:
  SCHEDULE: "40 4 * * *"
  MAX_DOWNLOADS: "10"
  TV_HOST: "192.168.1.11"
